---
# indicate the hosts, name the tasks and what action to carry out
- hosts: all
  tasks:
  - name: Ping All Servers
    action: ping
    # you can add as many actions as needed to this play
  - debug: msg="If you can see me, then I ran successfully."
- hosts: dev
  tasks:
  - debug: msg="Checking to see if this group works."