---
- hosts: dev
# link the variables.yml file path
  vars_files:
  - variables.yml
  # here you place your variables
  vars:
    variable1: "PlayBookValue"
  tasks:
    - name: Variable Value
      debug: msg="The value is {{ variable1 }}"