---
# install it on all the servers
- hosts: dev
  tasks:
  # yum is a package manager
    - yum:
        name:
          - httpd
        state: present
    # now run it as a service
    - service: name=httpd state=started enabled=yes