---
- hosts: qa
# creating variables to experiment with conditionals
  vars:
    system: "Linux"
    color: "Teal"
  tasks:
    # - debug: var=hostvars
    - debug: var=ansible_system
    - debug: var=color
    # now the conditional
      when: system == "Linux"
    # make the tasks run on every item (iteration)
    - debug: var=item
      with_items:
      - name: folarin
        country: Nigeria
      - name: IK
        country: US
      - name: Kola
        country: UK
      - name: Deola
        country: Nigeria